### PR TITLE
DAO Snapshot section

### PR DESCRIPTION
**Pull request by aleemrehmtulla**
DAO Snapshot section of homepage in dao.vitadao.com

Screen Shot 2021-12-08 at 1 49 52 PM

### CODE REVIEW

**Comment by schmackofant** [comment]
Thanks for the draft @aleemrehmtulla, that's a good start 👍 

Some initial feedback:
- The PR should always be named after the feature/change you're working on. Makes it much easier for all team members and contributors to see what it's about. 
- The gap between the boxes seems really wide to me. You can take a look at the figma file to see how the designer envisioned it: 
Screenshot 2021-12-08 at 09 57 34

- The boxes don't seem to take all the space that's available to them, which looks a bit off at some resolutions: 
Screenshot 2021-12-08 at 10 05 20
You should probably use `w-full` instead of pre-defined widths. Then you can control the width via changing the `grid-cols-XY` for different breakpoints. You're also switching between `grid` and `flex` which is not necessary.

- Make sure to check margins and gaps are correct for every resolution: 
Screenshot 2021-12-08 at 10 10 09

**Comment by aleemrehmtulla** [comment]
> Thanks for the draft @aleemrehmtulla, that's a good start 👍
> 
> Some initial feedback:
> 
> * The PR should always be named after the feature/change you're working on. Makes it much easier for all team members and contributors to see what it's about. It's also a best practice to give a little bit of context in the PR description.
> * The gap between the boxes seems really wide to me. You can take a look at the figma file to see how the designer envisioned it:
>   Screenshot 2021-12-08 at 09 57 34
> * The boxes don't seem to take all the space that's available to them, which looks a bit off at some resolutions:
>   Screenshot 2021-12-08 at 10 05 20
>   You should probably use `w-full` instead of pre-defined widths. Then you can control the width via changing the `grid-cols-XY` for different breakpoints. You're also switching between `grid` and `flex` which is not necessary.
> * Make sure to check margins and gaps are correct for every resolution:
>   Screenshot 2021-12-08 at 10 10 09

Gotcha ✅

Implemented the better media quires to only use grid, have a full width & smaller gaps to follow figma better--sorry for bad pr practices, not used to collaborative projects 😅

**Comment by schmackofant** [comment]
Thanks, Aleem… great work!

I made some changes to polish this a bit further. Some notes:
- Try to avoid explicit paddings/heights/weights whenever possible, to make the elements as flexible as can be. E.g. you can use flexbox `space-between` to align the first child element to the top and the second to the bottom, instead of using an explicit padding-top for the second child element. Keeps it "future-proof" in case we decide to change dimensions later.
- Before you add new helpers and variables to a design system, think about if this is really something that will be used in multiple or many places in the future, or if you just need it one time. E.g. you can use `opacity` to create text that is a lighter variant of the Vita purple instead of introducing a whole new color variable.

We will leave this a draft for now, until we have figured out how to best query the treasury and token data on our site.

**Review by schmackofant — APPROVED** [review]

**Comment by schmackofant** [comment]
I quickly extracted the section in its own component, so we can easily add it later on. Thanks again and this can be merged  🎉

**Pull request merged**
